server:
  port: 8082

spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:h2:mem:profiledb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
